name: Build & deploy

on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      
      - name: Get dependencies
        run: npm install

      - name: Build
        run: npm build
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
    
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "tiagorodriguessousa9@gmail.com"
          git config --global user.name "Tiago Rodrigues Sousa"
          cd dist
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.TOKEN }}@github.com:tiagors09/pokedex.git" prod:gh-pages
